<h1> Data Science MOOCs</h1>

> Online courses I've either completed or done a part of

- toc:true
- branch: master
- badges: true
- comments: true
- author: Thomas H. Simm
- categories: [coursera, mooc, data science, AI, Thomas Simm]

![](ghtop_images/header2.png)

<h2 id='LearnPy'> learnpython.org Python Development Course</h2>

In [9]:
import pandas as pd
import numpy as np

columns=['Course Title','Rating (0-10)']

dat=[['Variables and Types',7],
['Lists',7],
['Basic Operators',7],
['Strings',7],
['Conditions',7],
['Loops',7],
['Functions',7],
['Classes and Objects',7],
['Dictionaries',7],
['Modules and Packages',7],
['List Comprehensions',7],
['Regular Expressions',7],
['Exception Handling',7],
['Sets',7]]

lendat=np.shape(dat)[0]

ss = pd.DataFrame(data = dat,columns=columns)
ss.head(lendat)

            Course Title  Rating (0-10)
0    Variables and Types              7
1                  Lists              7
2        Basic Operators              7
3                Strings              7
4             Conditions              7
5                  Loops              7
6              Functions              7
7    Classes and Objects              7
8           Dictionaries              7
9   Modules and Packages              7
10   List Comprehensions              7
11   Regular Expressions              7
12    Exception Handling              7
13                  Sets              7

![](ghtop_images/LearnPy.png)

<h2 id='IBM_Data'> IBM Data Science Professional Certificate</h2>

In [10]:

columns=['Course Title','Expected Time (h)','Rating (0-10)']
#IBMds = pd.DataFrame(columns=columns)

dat = [['What is Data Science?',9,6],
    ['Tools for Data Science',17,6],
    ['Data Science Methodology',8,6],
    ['Python for Data Science, AI & Development',17,6],
    ['Python Project for Data Science',6,6],
    ['Databases and SQL for Data Science with Python',18,6],
    ['Data Analysis with Python',20,6],
    ['Data Visualization with Python',13,6],
    ['Machine Learning with Python',21,6],
    ['Applied Data Science Capstone',47,6]]

ss = pd.DataFrame(data = dat,columns=columns)

ssTot=pd.DataFrame(data = [['IBM Data- Overview',ss['Expected Time (h)'].sum(),ss['Rating (0-10)'].mean()]],columns=columns)
ss=ssTot.append(ss)
ss.reset_index(inplace=True,drop=True)
ss.head(12)

,Course Title,Expected Time (h),Rating (0-10)
0,IBM Data- Overview,176,6.0
1,What is Data Science?,9,6.0
2,Tools for Data Science,17,6.0
3,Data Science Methodology,8,6.0
4,"Python for Data Science, AI & Development",17,6.0
5,Python Project for Data Science,6,6.0
6,Databases and SQL for Data Science with Python,18,6.0
7,Data Analysis with Python,20,6.0
8,Data Visualization with Python,13,6.0
9,Machine Learning with Python,21,6.0
10,Applied Data Science Capstone,47,6.0

![](ghtop_images/IBM_Data.png)